version: '3'
services:
  animalcrossing-redis:
    container_name: animalcrossing-redis
    image: redis:5
    ports:
      - "6379:6379"
      
  animalcrossing-web:
    container_name: animalcrossing-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - RedisUrl=animalcrossing-redis
    depends_on:
      - animalcrossing-redis